console.log(`a`)        // 'a'
console.log('a')        // 'a'
console.log('\a')       // 'a'
console.log('\141')     // 'a'
console.log('\x61')     // 'a'
console.log('\u0061')   // 'a'
console.log('\u{0061}') // 'a'